// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"strings"
)

func Link(la LinkAttrs) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(la.Href))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `web/component/link.templ`, Line: 9, Col: 33}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, la.ToAttr())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</a>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

type LinkAttrs struct {
	Href          string
	ID            string
	Class         string
	HxMethod      string
	HxAction      string
	HxSwap        string
	OverrideClass bool
}

func (la *LinkAttrs) ToAttr() templ.Attributes {
	attrs := templ.Attributes{
		"href":  templ.SafeURL(la.Href),
		"class": la.ClassAttr(),
	}
	attrs = la.AddIDAttr(attrs)
	attrs = la.AddHxMethod(attrs)
	attrs = la.AddHxSwap(attrs)
	return attrs
}

func (la *LinkAttrs) ClassAttr() string {
	defaultClass := "font-semibold text-teal-500 hover:text-teal-400"

	if la.OverrideClass {
		return CssClassOverride(defaultClass, la.Class)
	} else {
		return CssClass(defaultClass, la.Class)
	}
}

func (la *LinkAttrs) AddIDAttr(attrs templ.Attributes) templ.Attributes {
	if la.ID != "" {
		attrs["id"] = la.ID
	}
	return attrs
}

func (la *LinkAttrs) AddHxMethod(attrs templ.Attributes) templ.Attributes {
	if la.HxMethod != "" {
		la.HxMethod = strings.ToLower(la.HxMethod)
		attrs[fmt.Sprintf("hx-%s", la.HxMethod)] = la.HxAction
	}
	return attrs
}

func (la *LinkAttrs) AddHxSwap(attrs templ.Attributes) templ.Attributes {
	if la.HxSwap != "" {
		attrs["hx-swap"] = la.HxSwap
	}
	return attrs
}

var _ = templruntime.GeneratedTemplate
